- apps/evm/src/pages/Bridge/components/BridgeStatus/WithdrawStatus.tsx
> chore(evm): add bridge exception capture tracking

- apps/evm/src/components/LoginSection/LoginSection.tsx
- apps/evm/src/pages/SignUp/SignUp.tsx
> fix(evm): fusion auth chain check missing

- apps/evm/src/pages/Bridge/components/BridgeForm/BtcBridgeForm.tsx
> fix(evm): onramp quote error

- apps/evm/src/lib/react-query/keys.ts
- apps/evm/src/pages/Bridge/components/BridgeForm/BtcBridgeForm.tsx
- apps/evm/src/utils/onramp-api-client.ts
- packages/ui/src/components/TokenInput/TokenInputBalance.tsx
> feat(evm): add liquidity check for onramp

- apps/evm/src/pages/Bridge/Bridge.tsx
> feat(evm): add bitcoin bridge search params

- apps/evm/src/pages/Bridge/components/BridgeForm/BtcBridgeForm.tsx
- packages/sats-wagmi/src/hooks/index.ts
- packages/sats-wagmi/src/hooks/useFeeEstimate.tsx
- packages/sats-wagmi/src/hooks/useFeeRate.tsx
- packages/tokens/src/constants/common.ts
- packages/utils/src/index.ts
- packages/utils/src/utxo.ts
Assumes all inputs and outputs are P2WPKH
> feat: add helpers to estimate fees

- apps/evm/src/pages/Wallet/components/TokenTable/TokenTable.tsx
> feat(evm): add navigation to onramp from wallet

- apps/evm/src/pages/Bridge/Bridge.tsx
> fix(evm): fraud proofs docs link

- apps/evm/src/pages/Bridge/components/BridgeForm/BtcBridgeForm.tsx
- apps/evm/src/pages/Fusion/components/PartnersSection/PartnerSection.tsx
> Bump min btc amount

- apps/hybrid-pay/src/hooks/useTotalBalance.ts
- apps/hybrid-pay/src/pages/Wallet/components/Hero/Hero.tsx
> fix: total balance display

- packages/connect-ui/src/component/ConnectModal/ConnectModal.tsx
> fix(connect-ui): wallet-connect modal

- apps/hybrid-pay/src/pages/Send/Send.style.tsx
- apps/hybrid-pay/src/pages/Send/Send.tsx
- apps/hybrid-pay/src/pages/Send/components/ScannerModal/ScannerModal.tsx
> feat: add qr code scanner

- packages/connect-ui/src/component/ConnectModal/ConnectModal.tsx
> chore: update privacy policy

- apps/evm/src/pages/SignUp/SignUp.tsx
> refactor(evm): replace sign-up twitter follow link

- apps/evm/src/indexer/bridge/README.md
- apps/evm/src/indexer/bridge/new_testnet_bridge_deposits.json
- apps/evm/src/indexer/bridge/new_testnet_bridge_withdraws.json
The PR adds
- new testnet subgraph config for standard bridge + custom UDSC bridge + custom wseth bridge
- update readme with new GQL link
> chore: add new testnet subgraph bridge configs

- apps/evm/src/constants/assets.ts
> feat(evm): add t token

- apps/evm/next.config.mjs
> fix(evm): api route

- apps/bob-pay/src/app/[lang]/providers.tsx
- apps/bob-pay/src/lib/react-query/index.ts
- apps/bob-pay/src/types/fetch.ts
- apps/evm/src/app/[lang]/(bridge)/hooks/useGetBridgeTransactions.ts
- apps/evm/src/app/[lang]/apps/hooks/useGetPodiumData.tsx
- apps/evm/src/app/[lang]/fusion/components/UserInfo/UserInfo.tsx
- apps/evm/src/app/[lang]/nested-providers.tsx
- apps/evm/src/app/[lang]/providers.tsx
- apps/evm/src/app/[lang]/sign-up/SignUp.tsx
- apps/evm/src/components/LoginButton/LoginButton.tsx
- apps/evm/src/components/SignUpButton/SignUpButton.tsx
- apps/evm/src/connect-ui/component/AuthButton/__tests__/AuthButton.test.tsx
- apps/evm/src/connect-ui/component/ConnectWallet/__tests__/ConnectWallet.test.tsx
- apps/evm/src/hooks/tests/useLogin.test.tsx
- apps/evm/src/hooks/tests/useLogout.test.tsx
- apps/evm/src/hooks/tests/useSignUp.test.tsx
- apps/evm/src/hooks/useGetUser.ts
- apps/evm/src/hooks/useLogin.ts
- apps/evm/src/hooks/useLogout.ts
- apps/evm/src/hooks/useLotteryRoll.ts
- apps/evm/src/hooks/usePublicClient.ts
- apps/evm/src/hooks/useSignUp.ts
- apps/evm/src/lib/react-query/index.ts
- apps/evm/src/lib/react-query/keys.ts
- apps/evm/src/locales/en.po
- apps/evm/src/locales/zh.po
- apps/evm/src/types/fetch.ts
- apps/evm/src/utils/api-client.ts
Closes # 
- Did some adjustments to QueryClient [(here)](https://tanstack.com/query/latest/docs/framework/react/guides/ssr#initial-setup), specially added some default stale and cache time.
- Removed unnecessary calls to `/me`
- Prolonged some request intervals
> fix(evm): reduce fusion related calls

- apps/evm/src/hooks/tests/useWalletClient.test.ts
- apps/evm/src/hooks/useWalletClient.ts
> Fix app crash in browsers with no injected wallet

- apps/evm/src/app/[lang]/fusion/components/UserInfo/MultipliersModal.tsx
> fix(evm): multipliers table

- apps/evm/src/app/[lang]/(bridge)/bridge/components/BridgeForm/BobBridgeForm.tsx
- packages/ui/src/components/TokenInput/SelectableTokenInput.tsx
- packages/ui/src/components/TokenInput/__tests__/TokenInput.test.tsx
Closes # 
Test url https://bob-mainnet-git-fix-token-select-placeholder-distributed-crafts.vercel.app/en/bridge?network=ethereum&type=deposit
> fix: token select placeholder

- apps/evm/src/app/[lang]/(bridge)/bridge/components/BridgeForm/BobBridgeForm.tsx
- apps/evm/src/hooks/index.ts
- apps/evm/src/hooks/useBalances.ts
- apps/evm/src/hooks/usePublicClient.ts
- apps/evm/src/hooks/useSubscribeBalances.ts
- apps/evm/src/lib/wagmi/mainnet.ts
- apps/evm/src/lib/wagmi/sepolia.ts
> Subscribe BobBridgeForm for balance updates

- apps/evm/src/app/[lang]/fusion/components/Strategies/StrategyCard.tsx
- apps/evm/src/locales/en.po
- apps/evm/src/locales/zh.po
> fix(evm): strategies copy

- apps/evm/src/app/[lang]/(bridge)/stake/components/StakeForm/StakeForm.tsx
- apps/evm/src/app/[lang]/(bridge)/stake/components/StakeRewards/StakeRewards.tsx
- apps/evm/src/app/[lang]/(bridge)/stake/components/StakeRewards/index.tsx
- apps/evm/src/app/[lang]/(bridge)/stake/components/StakeTable/StakeTable.tsx
- apps/evm/src/app/[lang]/(bridge)/stake/components/StrategyModal/StrategyModal.tsx
- apps/evm/src/app/[lang]/(bridge)/stake/hooks/useGetStakingStrategies.ts
- apps/evm/src/locales/en.po
- apps/evm/src/locales/zh.po
> feat(evm): add missing data to stake modal

- apps/evm/src/app/[lang]/(bridge)/bridge/components/ExternalBridgeForm/ExternalBridgeForm.tsx
> feat(evm): move tech external bridge up

- apps/evm/src/app/[lang]/fusion/Fusion.tsx
> Update link for op superusers banner

- apps/evm/src/app/[lang]/(bridge)/bridge/Bridge.tsx
- apps/evm/src/app/[lang]/(bridge)/bridge/components/BridgeForm/BobBridgeForm.tsx
- apps/evm/src/app/[lang]/(bridge)/bridge/components/BridgeForm/BridgeForm.tsx
- apps/evm/src/app/[lang]/(bridge)/bridge/components/BridgeForm/BtcBridgeForm.tsx
- apps/evm/src/app/[lang]/(bridge)/hooks/useGatewayForm.ts
- apps/evm/src/locales/en.po
- apps/evm/src/locales/zh.po
- apps/evm/src/types/session-storage.ts
> feat(evm): add symbol query support

- apps/evm/src/app/[lang]/fusion/components/UserInfo/MultipliersModal.tsx
> fix(evm): add lbtc to yield multiplier table

- apps/evm/src/app/[lang]/(bridge)/components/BannerCarousel/BannerCarousel.tsx
> Fix babylon link

- apps/evm/src/app/[lang]/fusion/components/UserInfo/UserInfo.tsx
- apps/evm/src/locales/en.po
- apps/evm/src/locales/zh.po
> feat(evm): add 24h tooltip copy change

- apps/evm/src/app/[lang]/(bridge)/bridge/components/ExternalBridgeForm/ExternalBridgeCard.tsx
> Update link to meson protocol

- apps/evm/src/components/AnimantedAmount/AnimantedAmount.tsx
- apps/evm/src/components/BabyPoints/BabyPoints.tsx
- apps/evm/src/components/Layout/FusionPopover.tsx
> fix(evm): baby points rounding

- apps/evm/src/app/[lang]/fusion/Fusion.tsx
> Revert past harvest check

- apps/evm/src/app/[lang]/(bridge)/components/GatewayStatus/GatewayStep.tsx
> fix(evm): show complete on partial success

- apps/evm/src/app/[lang]/(bridge)/components/BridgeStatus/WithdrawStatus.tsx
- apps/evm/src/locales/en.po
- apps/evm/src/locales/zh.po
> fix(evm): improve error handling on prove/finalize bridge withdraw

- apps/evm/src/app/[lang]/(bridge)/utils/stakeData.tsx
> feat(evm): enable solv

- apps/evm/src/app/[lang]/(bridge)/bridge/Bridge.tsx
- apps/evm/src/app/[lang]/(bridge)/bridge/components/BridgeForm/BobBridgeForm.tsx
- apps/evm/src/app/[lang]/(bridge)/bridge/components/BridgeForm/BridgeForm.tsx
- apps/evm/src/locales/en.po
- apps/evm/src/locales/zh.po
- packages/ui/src/components/Tabs/Tab.tsx
- packages/ui/src/components/Tabs/Tabs.stories.tsx
- packages/ui/src/components/Tabs/Tabs.tsx
- packages/ui/src/components/Tabs/index.tsx
> fix(evm): improve bridge tab and origin flow

- apps/evm/src/app/[lang]/(bridge)/bridge/Bridge.tsx
- apps/evm/src/app/[lang]/(bridge)/components/BridgeStatus/TimeStep.tsx
- apps/evm/src/app/[lang]/(bridge)/components/TransactionList/TransactionList.tsx
- apps/evm/src/app/[lang]/(bridge)/stake/Stake.tsx
- apps/evm/src/app/[lang]/(bridge)/stake/hooks/tests/useGetStakingStrategies.test.tsx
- apps/evm/src/app/[lang]/(bridge)/stake/hooks/useGetStakingStrategies.ts
- apps/evm/src/app/[lang]/(bridge)/stake/hooks/useStrategiesContractData.ts
- apps/evm/src/locales/en.po
- apps/evm/src/locales/zh.po
> chore: calculate user staked in tokens

- apps/evm/src/app/[lang]/(bridge)/stake/components/StakeTable/StakeTable.tsx
> fix(evm): show missing manage buttons

- apps/evm/src/app/[lang]/(bridge)/utils/stakeData.tsx
> fix(evm): strategies security review links

- packages/sats-wagmi/package.json
- pnpm-lock.yaml
> Fix okx taproot address psbt signing 

- apps/evm/src/app/[lang]/fusion/Fusion.tsx
> Hide welcome modal

- apps/evm/src/app/[lang]/fusion/components/TopUserModal/TopUserModal.tsx
- apps/evm/src/hooks/useLogin.ts
- apps/evm/src/hooks/useSignUp.ts
Closes # 
can not send data as object because GA interprets them as `[object Object]`.
each field must be primitive data type
> Send primitive values as ga data

- apps/evm/src/app/[lang]/(bridge)/components/TransactionList/TransactionList.tsx
> fix: firefox virtual item mesure element

- apps/evm/src/hooks/useLogin.ts
- apps/evm/src/hooks/useSignUp.ts
> Wrap addresses in quotes to prevent number coercion

- apps/evm/src/app/[lang]/(bridge)/bridge/components/BridgeForm/BridgeForm.tsx
- apps/evm/src/app/[lang]/(bridge)/stake/components/StakeForm/StakeForm.tsx
> Send stake and bridge gateway data to GA

- apps/evm/src/app/[lang]/fusion/components/UserInfo/UserInfo.tsx
> fix: babylon logo on fusion page

- apps/evm/src/components/AnimantedAmount/AnimantedAmount.tsx
- apps/evm/src/components/BabyPoints/BabyPoints.tsx
> fix(evm): add max 2 decimals places for baby point

- apps/evm/src/app/[lang]/(bridge)/stake/components/StakeTable/StakeTable.tsx
> fix(evm): filter strategies without info

- apps/evm/src/constants/assets.ts
> fix(evm): asset list

- apps/evm/src/constants/assets.ts
> fix(evm): lombard address

- apps/evm/src/app/[lang]/(bridge)/stake/hooks/useStrategiesContractData.ts
> fix: usd deposit amount calculations for segment

- apps/evm/src/lib/wagmi/config.ts
> fix(evm): wagmi config

- apps/evm/src/app/[lang]/(bridge)/stake/constants/strategies.tsx
> fix(evm): remove babylon warnings

- apps/evm/src/app/[lang]/fusion/components/LotterySections/LotteryModal/LotteryModal.tsx
> Fix lunar lottery fireworks

- apps/evm/src/app/[lang]/(bridge)/bridge/components/BridgeForm/BobBridgeForm.tsx
- apps/evm/src/app/[lang]/(bridge)/bridge/components/BridgeForm/BridgeForm.tsx
- apps/evm/src/app/[lang]/(bridge)/stake/components/StrategyForm/StrategyForm.tsx
- apps/evm/src/connect-ui/component/ConnectModal/ConnectModal.tsx
- apps/evm/src/hooks/useLogin.ts
- apps/evm/src/hooks/useSignUp.ts
> chore: gtm to ga events

- apps/evm/src/app/[lang]/(bridge)/bridge/components/BridgeForm/BridgeForm.tsx
- apps/evm/src/connect-ui/component/ConnectModal/ConnectModal.tsx
> chore: json stringify evm addresses

- apps/evm/src/app/[lang]/(bridge)/bridge/components/BridgeForm/BobBridgeForm.tsx
- apps/evm/src/connect-ui/component/ConnectModal/ConnectModal.tsx
> fix: mm snap connect name is undefined

- apps/evm/src/app/[lang]/fusion/components/Quests/Quests.style.tsx
- apps/evm/src/app/[lang]/fusion/components/Quests/Quests.tsx
> feat(evm): add layer3 quest

- apps/evm/src/locales/en.po
- apps/evm/src/locales/zh.po
> fix: update lingui keys

- apps/evm/src/app/[lang]/(bridge)/stake/components/StrategyDetails/StrategyDetails.tsx
- apps/evm/src/app/api/strategies/route.ts
> fix: ticker -> symbol for deposit token

- apps/evm/src/components/Layout/Header.tsx
- apps/evm/src/components/Layout/Sidebar.tsx
- apps/evm/src/components/SocialsGroup/SocialsGroup.tsx
- apps/evm/src/locales/en.po
- apps/evm/src/locales/zh.po
> Move social icons to header

- apps/evm/src/components/Layout/Header.tsx
- apps/evm/src/components/Layout/Sidebar.tsx
- apps/evm/src/locales/en.po
- apps/evm/src/locales/zh.po
> Remove docs link

- apps/evm/src/locales/zh.po
> Cleanup zh po file

- apps/evm/src/app/[lang]/fusion/Fusion.tsx
- apps/evm/src/locales/en.po
- apps/evm/src/locales/zh.po
> fix: fusion x banner

- apps/evm/package.json
- packages/sats-wagmi/package.json
- pnpm-lock.yaml
> chore: bump sats wagmi and sdk versions

- apps/evm/src/lib/wagmi/mainnet.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
Closes # 
update eth mainnet chain config with new rpm url
in sentry report it's clear that tenderly node is throwing connection errors
> fix: all promises were rejected sentry error

- apps/evm/src/app/api/fusion/check-cookie/route.ts
- apps/evm/src/hooks/tests/useLogin.test.tsx
- apps/evm/src/hooks/tests/useSignUp.test.tsx
- apps/evm/src/hooks/useGetUser.ts
- apps/evm/src/hooks/useLogin.ts
- apps/evm/src/hooks/useSignUp.ts
- apps/evm/src/locales/en.po
- apps/evm/src/locales/zh.po
- apps/evm/src/utils/api-client.ts
> fix(evm): reduce me fail rate

- apps/evm/src/app/[lang]/fusion/Fusion.tsx
- apps/evm/src/app/[lang]/fusion/page.tsx
- apps/evm/src/locales/en.po
- apps/evm/src/locales/zh.po
> Revert "chore: check user session server side"
